import { NextResponse } from "next/server";

// Public, read-only "what's Damian listening to" endpoint.
//
// Authorization happens exactly once, outside of this app: a refresh token is
// generated by hand (via a one-time Spotify login) and stored as the
// SPOTIFY_REFRESH_TOKEN env var. Every request here just exchanges that
// refresh token for a short-lived access token server-side and reads Spotify
// on the visitor's behalf — no visitor ever sees a login prompt, a client ID,
// or any Spotify UI at all.
export const dynamic = "force-dynamic";

interface SpotifyArtist {
  name: string;
}

interface SpotifyImage {
  url: string;
}

interface SpotifyTrack {
  name?: string;
  artists?: SpotifyArtist[];
  duration_ms?: number;
  external_urls?: { spotify?: string };
  album?: { images?: SpotifyImage[] };
}

interface NowPlayingPayload {
  ok: boolean;
  isPlaying: boolean;
  title: string | null;
  artist: string | null;
  albumArt: string | null;
  trackUrl: string | null;
  durationMs: number;
  progressMs: number;
  source: "live" | "recent" | "none";
  serverTime: number;
}

function emptyPayload(): NowPlayingPayload {
  return {
    ok: true,
    isPlaying: false,
    title: null,
    artist: null,
    albumArt: null,
    trackUrl: null,
    durationMs: 0,
    progressMs: 0,
    source: "none",
    serverTime: Date.now(),
  };
}

function normalizeTrack(track: SpotifyTrack) {
  return {
    title: track.name || "Spotify",
    artist: (track.artists || []).map((artist) => artist.name).join(", ") || "Spotify",
    albumArt: track.album?.images?.[0]?.url || null,
    trackUrl: track.external_urls?.spotify || null,
    durationMs: track.duration_ms || 0,
  };
}

// Cached in module scope so it survives across requests on a warm serverless
// instance. Spotify access tokens last an hour — refreshing on every single
// poll (every page load, plus every 15s while a visitor is on the page) was
// adding a whole extra network round-trip to Spotify for no reason, which is
// exactly the kind of delay that turns a brief loading flash into a visible one.
let cachedAccessToken: { token: string; expiresAt: number } | null = null;

async function getAccessToken(): Promise<string | null> {
  if (cachedAccessToken && cachedAccessToken.expiresAt > Date.now()) {
    return cachedAccessToken.token;
  }

  const clientId = process.env.SPOTIFY_CLIENT_ID;
  const clientSecret = process.env.SPOTIFY_CLIENT_SECRET;
  const refreshToken = process.env.SPOTIFY_REFRESH_TOKEN;

  if (!clientId || !clientSecret || !refreshToken) {
    return null;
  }

  // Confidential-client refresh (Basic auth with the client secret). This is
  // a server-only integration — the secret lives in a Vercel env var and is
  // never sent to a browser — so there's no need for the public-client PKCE
  // dance a visitor-facing login flow would require.
  const basicAuth = Buffer.from(`${clientId}:${clientSecret}`).toString("base64");

  const response = await fetch("https://accounts.spotify.com/api/token", {
    method: "POST",
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      Authorization: `Basic ${basicAuth}`,
    },
    body: new URLSearchParams({
      grant_type: "refresh_token",
      refresh_token: refreshToken,
    }),
    cache: "no-store",
  });

  if (!response.ok) {
    return null;
  }

  const data = await response.json();

  if (!data.access_token) {
    return null;
  }

  // Trim 60s off the real expiry as safety margin against clock drift/latency.
  cachedAccessToken = {
    token: data.access_token,
    expiresAt: Date.now() + (data.expires_in || 3600) * 1000 - 60_000,
  };

  return cachedAccessToken.token;
}

const sleep = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));

// Spotify's currently-playing endpoint occasionally returns a 204/empty
// response for a brief moment — often right around a track change, sometimes
// just API flakiness — even though something is genuinely playing. Treating
// that single blip as "nothing playing" and falling back to recently-played
// (the *previous* track) made the card visibly jump backward for one 15s
// poll before self-correcting. One quick retry filters almost all of that
// out, since real "nothing playing" states don't clear in under a second.
async function fetchCurrentlyPlaying(authHeader: { Authorization: string }) {
  for (let attempt = 0; attempt < 2; attempt++) {
    const res = await fetch(
      "https://api.spotify.com/v1/me/player/currently-playing?additional_types=track,episode",
      { headers: authHeader, cache: "no-store" },
    );

    if (res.status === 200) {
      const data = await res.json();
      if (data?.item) {
        return data;
      }
    }

    if (attempt === 0) {
      await sleep(350);
    }
  }

  return null;
}

export async function GET() {
  const accessToken = await getAccessToken();

  if (!accessToken) {
    return NextResponse.json(emptyPayload(), { headers: { "Cache-Control": "no-store" } });
  }

  const authHeader = { Authorization: `Bearer ${accessToken}` };

  const data = await fetchCurrentlyPlaying(authHeader);

  if (data?.item) {
    const payload: NowPlayingPayload = {
      ok: true,
      isPlaying: Boolean(data.is_playing),
      progressMs: data.progress_ms || 0,
      source: "live",
      serverTime: Date.now(),
      ...normalizeTrack(data.item),
    };

    return NextResponse.json(payload, { headers: { "Cache-Control": "no-store" } });
  }

  // Still nothing after a retry — genuinely paused/stopped. Fall back to the
  // most recently played track so the card isn't just empty between songs.
  const recentRes = await fetch("https://api.spotify.com/v1/me/player/recently-played?limit=1", {
    headers: authHeader,
    cache: "no-store",
  });

  if (recentRes.ok) {
    const recentData = await recentRes.json();
    const track = recentData?.items?.[0]?.track;

    if (track) {
      const payload: NowPlayingPayload = {
        ok: true,
        isPlaying: false,
        progressMs: 0,
        source: "recent",
        serverTime: Date.now(),
        ...normalizeTrack(track),
      };

      return NextResponse.json(payload, { headers: { "Cache-Control": "no-store" } });
    }
  }

  return NextResponse.json(emptyPayload(), { headers: { "Cache-Control": "no-store" } });
}
